name: Docker Build and Push
on:
  push:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")
          BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          docker build -t cwz3021/2025cloud:${BRANCH_NAME}-${TIMESTAMP} .
      - name: Push Docker Image
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")
          BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          docker push cwz3021/2025cloud:${BRANCH_NAME}-${TIMESTAMP}
